version: '0.0.1'
services:
  client:
    stdin_open: true
    image: fpmip/mern-tstarter
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - src_files:/app/src
    restart: unless-stopped # always
volumes:
  src_files:
