version: '0.0.1'
services:
  client:
    stdin_open: true
    image: fpmip/mern-tstarter
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped # always
    volumes:
      - app-files:/app/
volumes:
  app-files:
    # external: true
